import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const results: Array<{ id: string; pass: boolean; detail: string }> = [];
const record = (id: string, pass: boolean, detail: string) => results.push({ id, pass, detail });
const required = ["docs/v0.3.2/00_RELEASE_CHARTER.md", "docs/v0.3.2/01_CONTEXT_PIPELINE.md", "docs/v0.3.2/02_STATE_AND_CONFIRMATION.md", "docs/v0.3.2/03_MEMORY_AND_PRIVACY.md", "docs/v0.3.2/04_ACCEPTANCE.md", "docs/v0.3.2/05_CONTEXT_DECISIONS_AND_LIFECYCLE.md", "contracts/v0.3.2/calibration-proposal.schema.json", "contracts/v0.3.2/end-day-proposal.schema.json", "contracts/v0.3.2/context-frame.schema.json", "test/context/context-foundation.test.ts", "test/observation/perception-cascade.test.ts", "test/context/intervention-decision.test.ts", "scripts/releases/v0.3.2/smoke.ts", "scripts/releases/v0.3.2/live.ts"];
record("C01", required.every((file) => existsSync(path.join(root, file))), `${required.filter((file) => existsSync(path.join(root, file))).length}/${required.length} V0.3.2 artifacts present`);
const files = ["src/core/operating-system/types.ts", "src/infrastructure/persistence/sqlite-operating-store.ts", "src/application/operating-system/operating-system.ts", "src/application/planning/codex-planner.ts", "src/interfaces/desktop/main.ts", "src/application/observation/observation-controller.ts", "src/core/observation/intervention-decision.ts", "src/core/context/context-engine.ts", "src/core/memory/retrieval.ts", "src/application/observation/perception-cascade.ts", "src/infrastructure/windows/windows-perception.ts", "ui/desktop/index.html", "ui/desktop/renderer.js", "ui/desktop/preload.cjs", "README.md"] as const;
const entries = await Promise.all(files.map(async (file): Promise<[string, string]> => {
  const source = await readFile(path.join(root, file), "utf8");
  return [file, source];
}));
const content = Object.fromEntries(entries) as Record<(typeof files)[number], string>;
const all = Object.values(content).join("\n");
record("C02", content["ui/desktop/index.html"].includes("setup-narrative") && !content["ui/desktop/index.html"].includes("current-position") && content["src/application/operating-system/operating-system.ts"].includes("CalibrationInput"), "initial calibration accepts one natural-language narrative");
record("C03", content["src/application/planning/codex-planner.ts"].includes("at most two questions") && content["src/core/operating-system/types.ts"].includes("clarification_questions") && content["src/core/operating-system/types.ts"].includes("InterpretedValue") && content["ui/desktop/renderer.js"].includes("interpreted_profile"), "interpretation exposes source, confidence, assumptions, and bounded questions");
record("C04", content["src/application/operating-system/operating-system.ts"].includes("draftEndDay") && content["src/application/operating-system/operating-system.ts"].includes("confirmEndDay") && content["src/infrastructure/persistence/sqlite-operating-store.ts"].includes("end_day_drafts"), "End Day interpretation is reversible and confirmation-gated");
record("C05", content["src/core/context/context-engine.ts"].includes("text_digest") && !content["src/infrastructure/persistence/sqlite-operating-store.ts"].includes("ocr_text") && !content["src/infrastructure/persistence/sqlite-operating-store.ts"].includes("accessibility_text"), "durable context excludes raw OCR and accessibility content");
record("C06", content["src/application/observation/observation-controller.ts"].includes("localPerception") && content["src/infrastructure/windows/windows-perception.ts"].includes("readAccessibility") && content["src/infrastructure/windows/windows-perception.ts"].includes("readOcr") && content["src/infrastructure/windows/windows-perception.ts"].includes("windowsHide: true"), "native perception is local, separated by signal, and authorization-bound");
record("C07", content["src/core/memory/retrieval.ts"].includes("embedLocally") && content["src/infrastructure/persistence/sqlite-operating-store.ts"].includes("searchMemories") && content["src/infrastructure/persistence/sqlite-operating-store.ts"].includes("fts_vector"), "vector memory and hybrid retrieval remain deterministic and local");
record("C08", content["src/infrastructure/persistence/sqlite-operating-store.ts"].includes("ON DELETE CASCADE") && content["src/infrastructure/persistence/sqlite-operating-store.ts"].includes("memory_index") && content["src/infrastructure/persistence/sqlite-operating-store.ts"].includes("schema_version: \"0.3.2\""), "migration, deletion, and backup disclose the V0.3.2 index boundary");
record("C09", !/(api\.openai\.com|new\s+OpenAI\s*\(|OPENAI_API_KEY)/.test(all) && content["src/application/planning/codex-planner.ts"].includes("CodexExecGateway"), "reasoning remains Codex CLI only with no direct OpenAI API path");
record("C10", content["src/interfaces/desktop/main.ts"].includes("contextIsolation: true") && content["src/interfaces/desktop/main.ts"].includes("sandbox: true") && content["src/interfaces/desktop/main.ts"].includes("setContentProtection(true)"), "Electron isolation and content protection remain enforced");
record("C11", content["src/application/observation/observation-controller.ts"].includes("automaticInterventionAllowed") && !content["src/core/context/context-engine.ts"].includes("setInterval") && !content["src/core/memory/retrieval.ts"].includes("setInterval"), "no new continuous model or perception loop was introduced");
record("C12", !/(Google Meet|Career Mode|send email|submit application)/i.test(content["src/application/operating-system/operating-system.ts"] + content["src/core/context/context-engine.ts"]), "meeting, career, and autonomous external actions remain excluded");
record("C13", content["src/application/observation/perception-cascade.ts"].indexOf("readAccessibility") < content["src/application/observation/perception-cascade.ts"].indexOf("input.capture") && content["src/application/observation/perception-cascade.ts"].indexOf("input.capture") < content["src/application/observation/perception-cascade.ts"].indexOf("readOcr") && content["src/application/observation/perception-cascade.ts"].includes("deterministicTrigger"), "perception order is UIA, then lazy OCR capture, with screenshot escalation limited to unresolved or deterministic failure context");
record("C14", content["src/core/observation/intervention-decision.ts"].includes("perception.confidence < 0.65") && content["src/core/observation/intervention-decision.ts"].includes("perception.confidence < 0.8") && content["src/core/observation/intervention-decision.ts"].includes("candidateSamples < 2") && content["src/core/observation/intervention-decision.ts"].includes("sameContextCooldownMs"), "confidence, stability, semantic delta, and same-context cooldown are deterministic");
record("C15", content["src/interfaces/desktop/main.ts"].includes("workingFrames") && content["src/interfaces/desktop/main.ts"].includes("onWorkingContextCleared") && content["src/infrastructure/persistence/sqlite-operating-store.ts"].includes("context_events") && content["src/infrastructure/persistence/sqlite-operating-store.ts"].includes("retention_class='event'"), "working context is volatile and durable context is event-bound with explicit retention");
record("C16", content["ui/desktop/index.html"].includes("context-view") && content["ui/desktop/renderer.js"].includes("renderContextDiagnostics") && content["src/core/operating-system/types.ts"].includes("context_diagnostics"), "context decisions are inspectable in a separate diagnostics surface");
record("C17", content["src/core/observation/intervention-decision.ts"].includes("wrong_context") && content["src/application/operating-system/operating-system.ts"].includes("recordContextFeedback") && content["src/core/observation/intervention-decision.ts"].includes("suppressedFingerprints"), "wrong-context feedback suppresses repetition for the session without autonomous adaptation");

function run(command: string) {
  const result = spawnSync("cmd.exe", ["/d", "/s", "/c", command], { cwd: root, encoding: "utf8", timeout: 300_000, maxBuffer: 30_000_000 });
  return { pass: result.status === 0, detail: result.status === 0 ? `${command} passed` : `${command} failed: ${(result.stderr || result.stdout || result.error?.message || "unknown").trim().slice(-1600)}` };
}
const quality = [run("npm run v031:validate"), run("npm run typecheck"), run("npm test"), run("npm run build"), run("node --check ui\\desktop\\renderer.js"), run("node --check ui\\desktop\\preload.cjs"), run("npm run v032:smoke"), run("npm audit --audit-level=high")];
record("C18", quality.every((item) => item.pass), quality.map((item) => item.detail).join("; "));
for (const result of results) console.log(`${result.pass ? "PASS" : "FAIL"} ${result.id} — ${result.detail}`);
console.log(`\nV0.3.2 automated release gate: ${results.filter((item) => item.pass).length}/${results.length} metrics passed.`);
if (results.some((item) => !item.pass)) process.exitCode = 1;
